### ISSUE TITLE
Would it be a way to show local images ?

### ISSUE THREAD

**Issue by jrouaix** [KmolYuan/reveal-yaml-rs#5]
Hello @KmolYuan 

I'm looking for a way to include static assets locally like img, gifs ...

I don't see any example where it's possible, not in the sources, but perhaps I just didn't seek enough ?

So is there a way ?

**Comment by KmolYuan** [comment]
Images can be inserted by [`img` key](https://docs.rs/reveal-yaml/latest/reveal_yaml/project/struct.Content.html#structfield.img) or Markdown syntax in `doc` key.

```yaml
# single
img:
  src: path/to/local-image.png
# multiple (placed horizontally)
img:
- src: img1.png
- src: img2.gif
```
